/*

 PIKACHU-SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char pikachu[] =
    {
        0x61, 0x61, 0x00, 0x31, 0x1F, 0x00, 0xDF, 0xC9,
        0xCF, 0xD0, 0x1E, 0x40, 0x3E, 0x40, 0x32, 0x0C,
        0x00, 0x00, 0x61, 0x61, 0x00, 0x31, 0xDF, 0xC0,
        0xDF, 0xC9, 0x0F, 0x50, 0x3E, 0x40, 0x32, 0x0C};

/* End of PIKACHU-SPRITES.C */
